name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  # Step 1: Run Tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Step 2: Build and Push Docker Image
  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # Runs only if the 'test' job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t <dockerhub-username>/<app-name>:latest .
          docker push <dockerhub-username>/<app-name>:latest

  # Step 3: Deploy to Azure App Service
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Runs only if the 'build-and-push' job succeeds

    steps:
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-azure-app-name>
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}