name: Node.js CI/CD Pipeline with Docker and Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: 'mo8hrb/devopsapp'  # Docker image name
  NODE_VERSION: '16'  # Node.js version

permissions:
  contents: read

jobs:
  test:
    name: Run Tests for Node.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # This job depends on the test job to pass

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Your Docker Hub username secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # Your Docker Hub token secret

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                               # Context for Docker build
          file: ./Dockerfile                       # Path to Dockerfile
          push: true                               # Push the image to Docker Hub
          tags: ${{ env.DOCKER_IMAGE }}:latest