name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

env:
  DOCKER_IMAGE: mo8hrb/devopsapp  # Replace with your Docker Hub username and repository name

jobs:
  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                              # Context for Docker build
          file: ./Dockerfile                      # Path to Dockerfile
          push: true                              # Push image to DockerHub
          tags: ${{ env.DOCKER_IMAGE }}:latest    # Tag the image with 'latest'