name: Node.js CI/CD Pipeline with Docker and Azure Deployment

on:
  push:
    branches: [ "master" ]  # Trigger the workflow for the master branch
  workflow_dispatch:

env:
  DOCKER_IMAGE: 'mo8hrb/devopsapp'  # Docker image name
  NODE_VERSION: '20'  # Node.js version
  AZURE_WEBAPP_NAME: 'DevOps-Mini-Projet'  # Replace with your Azure Web App name

permissions:
  contents: read

jobs:
  test:
    name: Run Tests for Node.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # This job depends on the test job to pass

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Your Docker Hub username secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # Your Docker Hub token secret

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                               # Context for Docker build
          file: ./Dockerfile                       # Path to Dockerfile
          push: true                               # Push the image to Docker Hub
          tags: ${{ env.DOCKER_IMAGE }}:latest      # Use the Docker image tag

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: docker-build-push  # This job depends on Docker build and push job
    environment:
      name: 'Production'

    steps:
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1  # Corrected Azure CLI action version

      - name: Login to Azure
        uses: azure/login@v1  # Corrected Azure login action
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the secret for Azure credentials

      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Publish profile secret
          images: ${{ env.DOCKER_IMAGE }}:latest  # Docker image to deploynode